language: python
sudo: false
branches:
only:
  - master
python:
  - "3.5"
  - "3.6"

env:
  - PYSAL_PLUS=false
  - PYSAL_PLUS=true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - if [ "$PYSAL_PLUS" == true ]; then
        echo 'plus testing'; pip install -r requirements_plus.txt;
        else conda install --yes --file requirements.txt;
    fi;
  - conda install --yes geopandas
  - pip install -r requirements_dev.txt

script:
  - python setup.py sdist >/dev/null
  - echo "check_stable=False" >libpysal/config.py
  - nosetests --with-doctest --verbose --with-coverage --cover-package=libpysal -I shapely_ext.py;
  #- cd doc; make pickle; make doctest
notifications:
    email:
        recipients:
            - sjsrey@gmail.com
            - levi.john.wolf@gmail.com
            - dfolch@gmail.com
            - daniel.arribas.bel@gmail.com
            - weikang9009@gmail.com
            - carsonfarmer@gmail.com
            - tayoshan@gmail.com
            - marynia.kolak@gmail.com
            - jgaboardi@gmail.com
            - phil.stphns@gmail.com
        on_success: always
        on_failure: always

after_success:
  - coveralls
