__version__ = "2.1.1"
# __version__ has to be defined in the first line

from .classifiers import (
    Box_Plot,
    BoxPlot,
    Equal_Interval,
    EqualInterval,
    Fisher_Jenks,
    FisherJenks,
    Fisher_Jenks_Sampled,
    FisherJenksSampled,
    HeadTail_Breaks,
    HeadTailBreaks,
    Jenks_Caspall,
    JenksCaspall,
    Jenks_Caspall_Forced,
    JenksCaspallForced,
    Jenks_Caspall_Sampled,
    JenksCaspallSampled,
    Max_P_Classifier,
    MaxP,
    Maximum_Breaks,
    MaximumBreaks,
    Natural_Breaks,
    NaturalBreaks,
    Quantiles,
    Percentiles,
    Std_Mean,
    StdMean,
    User_Defined,
    UserDefined,
    load_example,
    gadf,
    K_classifiers,
    KClassifiers,
    CLASSIFIERS,
)
