"""
Frozen package versions for PySAL meta-package.

This module provides version information for packages released in the current
version of the PySAL meta-package. It is designed to work both:
1. At build time (when generated by tools/frozen.py)
2. At runtime (by falling back to installed versions)

The `frozen_packages` dictionary maps package names to their released versions.
If explicit frozen versions are not available, it falls back to the currently
installed versions for graceful degradation.
"""

from pysal.base import _installed_version, memberships


def _get_frozen_packages():
    """
    Get the frozen package versions.

    For development installations or when frozen versions are not explicitly
    set, this falls back to using the installed versions. This ensures that
    Versions.released and Versions.check() work without raising errors.

    Returns
    -------
    dict
        Dictionary mapping package names to version strings.
    """
    versions = {}
    for package in memberships:
        versions[package] = _installed_version(package)
    return versions


frozen_packages = _get_frozen_packages()
